### ISSUE TITLE
[feat] Jwt Token 기능 구현

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#1]
## Description
Jwt 토큰 관련 기능 구현

## To-do
- [x] Jwt config 설정
- [x] user와 로그인 관련 파트 생성
- [x] service, controller 생성
- [x] 관련 dto 생성

## ETC
* 사용자 인증 및 로그인에 관한 기능은 무조건 들어갈 것이고, 와이어 프레임이 나오지 않아도 예상해서 개발할 수 있는 부분이기에 선 작업을 시작한다.
* 후 순위 작업으로는 Refresh Token 구현 및 와이어 프레임에 맞춰 코드 리팩토링이 있다.
