### ISSUE TITLE
[feat] Member 도메인 설계

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#19]
## Description
개발 핵심 도메인인 Member 도메인 설계입니다.

## To-do
- [x] Member 도메인 설계
- [x] City Enum type 객체 생성
- [x] Author 도메인 설계
