### ISSUE TITLE
[feat] 내 도서 관리 및 조회

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#44]
## Description
작가 마이페이지 속 내 도서 관리 페이지 제공을 위한 로직을 개발합니다.

## To-do
- [x] Book 엔티티 개발
- [x] 내 도서 관리 페이지 반환 API 작성
- [ ] 가능하다면 Book을 넣어줄 수 있는 관리자 객체 + 메서드를 만들자
