### ISSUE TITLE
[fix] 마이페이지 뷰 변경사항에 따른 서버 api 변경

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#48]
## Description
마이페이지 뷰 변경에 따라 데이터 필드 및 dto 변경

## To-do
- [x] dto 필드 변경
- [x] 데이터 필드 변경
- [x] Book 엔티티 생성
- [x] Book 엔티티 관련 메서드 생성
