### ISSUE TITLE
[feat] 홈 화면 API 구현

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#50]
## Description
홈 화면을 불러올 때 필요한 데이터들 리턴

## To-do
- [x] 주민 홈 화면 API 구현
- [x] 예정된 북토크 수, 지역 별 북토크 수 or null, 의정부시 전체 북토크
- [x] 작가 홈 화면 API 구현
- [x] 예정된 북토크 수, 북토크 많이 열린 지역 top3, 의정부시 전체 북토크
