### ISSUE TITLE
[feat] 지난 북토크 저장 메서드 구현

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#52]
## Description
스케줄링 및 완료된 북토크들 관리하는 메서드를 구현합니다

## To-do
- [x] 날짜 지난 북토크 상태를 완료된 북토크로 변경하는 메서드 구현
- [x] 멤버 도메인 내에 완료된 북토크 리스트 구현
- [x] 완료된 북토크 엔티티 생성
