### ISSUE TITLE
[refactor] 북토크 관련 API 예외 처리 추가

### ISSUE THREAD

**Issue by onpyeong** [SOPT-SOPHY/SOPHY-Server#58]
## Description
북토크 관련 API 예외 처리 추가

## To-do
- [ ] 책이 없는 경우
- [ ] city가 잘못된 경우
- [ ] time이 파싱이 안되는 경우
