### ISSUE TITLE
[feat] SpringSecurity 적용

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#6]
## Description
Jwt 토큰 검증 및 전달을 위한 Spring Security 적용 및 기존 코드 리팩토링

## To-do
- [x] 토큰 검증 및 전달 부 구현
- [x] Exception 및 Error 발생, 전달 부분 구현
- [x] SpringSecurity 적용
- [x] 기존 회원가입 및 로그인 코드 리팩토링
