### ISSUE TITLE
[refactor] 여러 데이터 로직 및 필드들 최적화

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#62]
## Description
코드 내에서 불필요하거나 통합할 수 있는 부분들 정리합니다.

## To-do
- [x] 멤버 내에 북토크 수를 따로 저장하는게 아니라 리스트에서 길이 추출
- [x] 완료된 북토크 연관관계 설정 메서드 추가
- [x] 북토크 참여 인원이 최대를 넘었을 때 예외처리 추가
