### ISSUE TITLE
[modify] authority를 이용해 권한 분리

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#66]
## Description
Spring Security를 이용해, 기존 boolean값으로 권한을 체크했던 것과 다르게 Filter단에서 권한 체크하는 로직 생성

## To-do
- [x] Authority Enum 필드 추가
- [x] Boolean 필드 지우고 Enum type으로 확인하게 변경
- [x] 작가 관련된 URI 한 컨트롤러에서 관리하게 변경
- [x] Security Config에 작가 URI에 대한 접근 권한 설정
- [x] token으로 유저 정보 받아오게 변경 -> Path Variable 사용 x
