### ISSUE TITLE
[modify] 화면 변경 사항에 맞춘 기능 분리

### ISSUE THREAD

**Issue by dong2ast** [SOPT-SOPHY/SOPHY-Server#88]
## Description
뷰가 분리됨에 따라 따로 분리되어 나오는 API나 삭제되어야 할 기능들을 작업합니다.

## To-do
- [ ] 예정된 북토크 조회 API 분리
- [ ] 소피스토리 반환 dto 변경
- [ ] 마이페이지 dto 변경
- [ ] 작가 마이페이지 내 도서 관리 api 생성 (혹은 그냥 dto?)
- [ ] 내 정보 수정 api 변경

## ETC
작가 프로필 및 주민 프로필은 기본적으론 추후에 새로운 issue로 생성할 예정이나 여기서 가능하다면 몇 가지는 작업할 예정
